import Foundation
#if os(macOS)
import Darwin

/// A bounded editable-source transfer is an ordinary directory with a closed
/// `source-archive.json` and `source/` tree. It never carries a built package,
/// credential, compiler, approval or device authority.
public struct WorkbenchPortableSourceArchiveManifest: Codable, Sendable, Equatable {
    public let schemaVersion: Int
    public let kind: String
    public let sourceHashVersion: Int
    public let sourceVersion: String
    public let project: WorkspaceProjectDocument
    public let files: [WorkbenchSourceFile]
}

public struct WorkbenchPortableSourceArchiveReceipt: Codable, Sendable, Equatable {
    public let archivePath: String
    public let sourceVersion: String
    public let projectId: String
    public let dashboardId: String
    public let fileCount: Int
    public let includedBytes: Int
}

public final class WorkbenchPortableSourceArchive {
    private let workspace: WorkspaceStore
    public init(workspace: WorkspaceStore) { self.workspace = workspace }

    /// Clone the exact current included source version into a new contained
    /// project. IDs are regenerated by the normal source transaction; no
    /// package, credential, device binding or local external path is copied.
    public func cloneCurrent(projectId: String, expectedSourceVersion: String,
                             destinationName: String? = nil) throws -> WorkbenchSourceProject {
        guard WorkspaceValidation.id(projectId), WorkspaceValidation.sha256(expectedSourceVersion),
              let selected = try workspace.current(),
              let project = selected.catalog.projects.first(where: { $0.projectId == projectId }),
              let path = try workspace.resolveProject(projectId) else { throw WorkspaceError.unavailable }
        let captured = try capture(path: path, project: project)
        guard captured.2 == expectedSourceVersion,
              try workspace.current()?.selectionGeneration == selected.selectionGeneration,
              try capture(path: path, project: project).2 == expectedSourceVersion else {
            throw WorkspaceError.conflict
        }
        let relative: String?
        if let destinationName {
            guard WorkspaceValidation.member(destinationName), !destinationName.contains("/"),
                  !destinationName.hasPrefix("."), destinationName.utf8.count <= 120 else {
                throw WorkspaceError.invalidPath
            }
            relative = "Screens/" + destinationName
        } else { relative = nil }
        return try WorkbenchContainedAuthoring(workspace: workspace).importVerifiedSource(
            descriptor: captured.0, files: captured.1, relativeDestination: relative)
    }

    public func export(projectId: String, expectedSourceVersion: String,
                       to destination: String) throws -> WorkbenchPortableSourceArchiveReceipt {
        guard WorkspaceValidation.id(projectId), WorkspaceValidation.sha256(expectedSourceVersion),
              WorkspaceValidation.absolute(destination), let overview = try workspace.current(),
              let project = overview.catalog.projects.first(where: { $0.projectId == projectId }),
              let sourcePath = try workspace.resolveProject(projectId) else { throw WorkspaceError.unavailable }
        let sourceKey = WorkspaceValidation.portableKey(sourcePath)
        let outputKey = WorkspaceValidation.portableKey(destination)
        guard outputKey != sourceKey, !outputKey.hasPrefix(sourceKey + "/"),
              !sourceKey.hasPrefix(outputKey + "/") else { throw WorkspaceError.invalidPath }
        let (descriptor, files, version) = try capture(path: sourcePath, project: project)
        guard version == expectedSourceVersion else { throw WorkspaceError.conflict }
        return try publish(descriptor: descriptor, files: files, version: version,
            project: project, sourcePath: sourcePath, destination: destination,
            expectedSelection: overview.selectionGeneration)
    }

    /// Export a retained immutable source snapshot by its exact full hash.
    /// It is checked against its recorded file inventory before publication.
    public func exportRetained(projectId: String, sourceVersion: String,
                               to destination: String) throws -> WorkbenchPortableSourceArchiveReceipt {
        guard WorkspaceValidation.id(projectId), WorkspaceValidation.sha256(sourceVersion),
              WorkspaceValidation.absolute(destination), let overview = try workspace.current(),
              let project = overview.catalog.projects.first(where: { $0.projectId == projectId }),
              project.location.path != nil else { throw WorkspaceError.unavailable }
        let sourcePath = overview.path + "/Workbench/History/Builds/" + sourceVersion + "/source"
        let (descriptor, files, version) = try captureRetained(path: sourcePath,
            project: project, requestedVersion: sourceVersion)
        return try publish(descriptor: descriptor, files: files, version: version,
            project: project, sourcePath: sourcePath, destination: destination,
            expectedSelection: overview.selectionGeneration) {
            try self.captureRetained(path: sourcePath, project: project,
                requestedVersion: sourceVersion)
        }
    }

    private func publish(descriptor: WorkspaceProjectDocument, files: [String: Data],
                         version: String, project: WorkspaceProject, sourcePath: String,
                         destination: String, expectedSelection: Int?,
                         recapture: (() throws -> (WorkspaceProjectDocument, [String: Data], String))? = nil)
        throws -> WorkbenchPortableSourceArchiveReceipt {
        let sourceKey = WorkspaceValidation.portableKey(sourcePath)
        let outputKey = WorkspaceValidation.portableKey(destination)
        guard outputKey != sourceKey, !outputKey.hasPrefix(sourceKey + "/"),
              !sourceKey.hasPrefix(outputKey + "/") else { throw WorkspaceError.invalidPath }
        let manifest = WorkbenchPortableSourceArchiveManifest(schemaVersion: 1,
            kind: "editable-source-project", sourceHashVersion: 1,
            sourceVersion: version, project: descriptor,
            files: files.keys.sorted { $0.utf8.lexicographicallyPrecedes($1.utf8) }.map { path in
                WorkbenchSourceFile(path: path, sha256: WorkbenchTransactionDigest.hex(files[path]!),
                    bytes: files[path]!.count)
            })
        let parentPath = (destination as NSString).deletingLastPathComponent
        let name = (destination as NSString).lastPathComponent
        guard WorkspaceValidation.absolute(parentPath), WorkspaceValidation.member(name),
              !name.contains("/") else { throw WorkspaceError.invalidPath }
        let parent = try WorkspaceFiles(path: parentPath, requiredPrivateRoot: false)
        guard !(try parent.exists(parent.fd, name)) else { throw WorkspaceError.conflict }
        let stageName = ".screenpunk-source-export-" + UUID().uuidString.lowercased()
        guard mkdirat(parent.fd, stageName, 0o700) == 0, fsync(parent.fd) == 0 else {
            throw WorkspaceError.unavailable
        }
        let stage = try WorkspaceFiles(path: parentPath + "/" + stageName)
        var published = false
        defer { if !published { try? removeOwnedStage(parent: parent, name: stageName, stage: stage) } }
        for path in manifest.files.map(\.path) {
            let parts = path.split(separator: "/").map(String.init)
            let folder = try stage.directory(["source"] + Array(parts.dropLast()), create: true)
            defer { close(folder) }
            try stage.write(folder, parts.last!, data: files[path]!, expected: nil)
        }
        try stage.write(stage.fd, "source-archive.json",
            data: WorkspaceJSON.encode(manifest), expected: nil)
        let (afterDescriptor, afterFiles, afterVersion) = try recapture?()
            ?? capture(path: sourcePath, project: project)
        guard afterDescriptor == descriptor, afterFiles == files, afterVersion == version,
              try workspace.current()?.selectionGeneration == expectedSelection else {
            throw WorkspaceError.conflict
        }
        try stage.verifyRoot(); try parent.verifyRoot()
        guard renameatx_np(parent.fd, stageName, parent.fd, name, UInt32(RENAME_EXCL)) == 0,
              fsync(parent.fd) == 0 else { throw WorkspaceError.unavailable }
        published = true
        return .init(archivePath: destination, sourceVersion: version,
            projectId: project.projectId, dashboardId: project.dashboardId,
            fileCount: files.count, includedBytes: files.values.reduce(0) { $0 + $1.count })
    }

    public func importSource(from archivePath: String, destinationName: String? = nil) throws
        -> WorkbenchSourceProject {
        guard WorkspaceValidation.absolute(archivePath), let selected = try workspace.current() else {
            throw WorkspaceError.invalidPath
        }
        let archive = try WorkspaceFiles(path: archivePath, requiredPrivateRoot: false)
        guard try topLevelNames(archive.fd) == ["source", "source-archive.json"] else {
            throw WorkspaceError.invalidSchema
        }
        let manifestBytes = try archive.read(archive.fd, "source-archive.json")
        guard let shape = try JSONSerialization.jsonObject(with: manifestBytes) as? [String: Any],
              Set(shape.keys) == ["schemaVersion", "kind", "sourceHashVersion", "sourceVersion", "project", "files"],
              let manifest = try? JSONDecoder().decode(WorkbenchPortableSourceArchiveManifest.self,
                  from: manifestBytes),
              let canonicalShape = try JSONSerialization.jsonObject(with: WorkspaceJSON.encode(manifest)) as? NSDictionary,
              canonicalShape.isEqual(to: shape),
              manifest.schemaVersion == 1, manifest.kind == "editable-source-project",
              manifest.sourceHashVersion == 1, WorkspaceValidation.sha256(manifest.sourceVersion),
              (1...2_000).contains(manifest.files.count) else { throw WorkspaceError.invalidSchema }
        let original = WorkspaceProject(projectId: manifest.project.projectId,
            dashboardId: manifest.project.dashboardId, name: manifest.project.name,
            location: .contained("Screens/import-probe"))
        try manifest.project.validate(matching: original)
        var files: [String: Data] = [:], total = 0
        var collisions = WorkspacePathCollisionDetector()
        for record in manifest.files {
            guard WorkspaceValidation.member(record.path),
                  !WorkspaceFiles.fixedSourceExcludes(record.path),
                  WorkspaceValidation.sha256(record.sha256),
                  (0...5 * 1024 * 1024).contains(record.bytes),
                  files[record.path] == nil else { throw WorkspaceError.invalidSchema }
            try collisions.insert(record.path)
            total += record.bytes
            guard total <= 25 * 1024 * 1024 else { throw WorkspaceError.limitExceeded }
            let parts = record.path.split(separator: "/").map(String.init)
            let folder = try archive.directory(["source"] + Array(parts.dropLast()))
            defer { close(folder) }
            let bytes = try archive.read(folder, parts.last!, maxBytes: 5 * 1024 * 1024)
            guard bytes.count == record.bytes,
                  WorkbenchTransactionDigest.hex(bytes) == record.sha256 else {
                throw WorkspaceError.conflict
            }
            files[record.path] = bytes
        }
        guard let descriptorBytes = files["screenpunk.project.json"],
              try WorkspaceJSON.decode(WorkspaceProjectDocument.self,
                  from: descriptorBytes, shape: .project) == manifest.project,
              files[manifest.project.screenConfig] != nil,
              files[manifest.project.entry] != nil,
              try WorkbenchSourceHasher.hash(files) == manifest.sourceVersion else {
            throw WorkspaceError.invalidSchema
        }
        let inventory = try archive.inventory(["source"],
            required: ["screenpunk.project.json", manifest.project.screenConfig, manifest.project.entry])
        guard inventory.includedFiles == Set(files.keys), inventory.omitted.isEmpty,
              inventory.files == files.count, inventory.bytes == total,
              try workspace.current()?.selectionGeneration == selected.selectionGeneration else {
            throw WorkspaceError.conflict
        }
        try archive.verifyRoot()
        let relative: String?
        if let destinationName {
            guard WorkspaceValidation.member(destinationName), !destinationName.contains("/"),
                  !destinationName.hasPrefix("."), destinationName.utf8.count <= 120 else {
                throw WorkspaceError.invalidPath
            }
            relative = "Screens/" + destinationName
        } else { relative = nil }
        return try WorkbenchContainedAuthoring(workspace: workspace).importVerifiedSource(
            descriptor: manifest.project, files: files, relativeDestination: relative)
    }

    /// Outside-workspace projects require an explicit choice. The catalog gets
    /// an opaque reference and the exact root inode is bound only locally.
    public func openExternal(at path: String, explicitExternal: Bool) throws -> WorkspaceProject {
        try openExternalVersioned(at: path, explicitExternal: explicitExternal).0
    }

    public func openExternalVersioned(at path: String, explicitExternal: Bool) throws
        -> (WorkspaceProject, String) {
        guard explicitExternal, WorkspaceValidation.absolute(path),
              let selected = try workspace.current() else { throw WorkspaceError.invalidPath }
        let root = try WorkspaceFiles(path: path, requiredPrivateRoot: false)
        let document = try WorkspaceJSON.decode(WorkspaceProjectDocument.self,
            from: root.read(root.fd, "screenpunk.project.json"), shape: .project)
        let project = WorkspaceProject(projectId: document.projectId,
            dashboardId: document.dashboardId, name: document.name,
            location: .external(UUID().uuidString.lowercased()))
        try document.validate(matching: project)
        let sourceVersion = try capture(path: path, project: project).2
        _ = try workspace.registerExternal(project, sourcePath: path,
            explicitExternal: true, expectedCatalogGeneration: selected.catalog.generation)
        return (project, sourceVersion)
    }

    /// Copy an explicitly registered external project into Screens, preserving
    /// project/dashboard identities. The original is never moved or rewritten.
    @discardableResult public func adoptExternal(projectId: String,
                                                expectedSourceVersion: String,
                                                name: String) throws -> WorkspaceProject {
        guard WorkspaceValidation.id(projectId), WorkspaceValidation.sha256(expectedSourceVersion),
              WorkspaceValidation.member(name), !name.contains("/"),
              !name.hasPrefix("."), name.utf8.count <= 120,
              let overview = try workspace.current(),
              let original = overview.catalog.projects.first(where: { $0.projectId == projectId }),
              original.location.referenceId != nil,
              let sourcePath = try workspace.resolveProject(projectId) else { throw WorkspaceError.unavailable }
        let (descriptor, files, version) = try capture(path: sourcePath, project: original)
        guard version == expectedSourceVersion else { throw WorkspaceError.conflict }
        let relative = "Screens/" + name
        try WorkspaceProjectLocation.contained(relative).validate()
        let root = try WorkspaceFiles(path: overview.path)
        let screens = try root.directory(["Screens"]); defer { close(screens) }
        let folderName = String(relative.split(separator: "/").last!)
        let stageName = ".screenpunk-adopt-" + UUID().uuidString.lowercased()
        guard mkdirat(screens, stageName, 0o700) == 0 else { throw WorkspaceError.unavailable }
        guard fsync(screens) == 0 else { throw WorkspaceError.unavailable }
        let screensRoot = try WorkspaceFiles(path: overview.path + "/Screens")
        let destination = try WorkspaceFiles(path: overview.path + "/Screens/" + stageName)
        var published = false
        defer { if !published { try? removeOwnedStage(parent: screensRoot, name: stageName,
            stage: destination) } }
        for path in files.keys.sorted() {
            let parts = path.split(separator: "/").map(String.init)
            let parent = try destination.directory(Array(parts.dropLast()), create: true)
            defer { close(parent) }
            try destination.write(parent, parts.last!, data: files[path]!, expected: nil)
        }
        let contained = WorkspaceProject(projectId: original.projectId,
            dashboardId: original.dashboardId, name: original.name,
            location: .contained(relative), collectionIds: original.collectionIds,
            sortOrder: original.sortOrder)
        let (copiedDescriptor, copiedFiles, copiedVersion) = try capture(
            path: overview.path + "/Screens/" + stageName, project: contained)
        guard copiedDescriptor == descriptor, copiedFiles == files,
              copiedVersion == version else { throw WorkspaceError.conflict }
        try destination.verifyRoot(); try root.verifyRoot()
        guard renameatx_np(screens, stageName, screens, folderName,
            UInt32(RENAME_EXCL)) == 0 else {
            throw errno == EEXIST ? WorkspaceError.conflict : WorkspaceError.unavailable
        }
        guard fsync(screens) == 0 else { throw WorkspaceError.unavailable }
        published = true
        try workspace.adoptExternal(projectId, to: relative,
            expectedCatalogGeneration: overview.catalog.generation) {
            let (currentDescriptor, currentFiles, currentVersion) = try self.capture(
                path: sourcePath, project: original)
            guard currentDescriptor == descriptor, currentFiles == files,
                  currentVersion == version else { throw WorkspaceError.conflict }
        }
        return contained
    }

    func capture(path: String, project: WorkspaceProject) throws
        -> (WorkspaceProjectDocument, [String: Data], String) {
        let root = try WorkspaceFiles(path: path, requiredPrivateRoot: false)
        let document = try WorkspaceJSON.decode(WorkspaceProjectDocument.self,
            from: root.read(root.fd, "screenpunk.project.json"), shape: .project)
        try document.validate(matching: project)
        let inventory = try root.inventory([], required: ["screenpunk.project.json",
            document.screenConfig, document.entry])
        var files: [String: Data] = [:]
        for member in inventory.includedFiles {
            let parts = member.split(separator: "/").map(String.init)
            let folder = try root.directory(Array(parts.dropLast())); defer { close(folder) }
            files[member] = try root.read(folder, parts.last!, maxBytes: 5 * 1024 * 1024)
        }
        guard files.values.reduce(0, { $0 + $1.count }) <= 25 * 1024 * 1024 else {
            throw WorkspaceError.limitExceeded
        }
        try root.verifyRoot()
        return (document, files, try WorkbenchSourceHasher.hash(files))
    }

    private func captureRetained(path: String, project: WorkspaceProject,
                                 requestedVersion: String) throws
        -> (WorkspaceProjectDocument, [String: Data], String) {
        let root = try WorkspaceFiles(path: path)
        let record = try JSONDecoder().decode(WorkbenchSourceHistoryEntry.self,
            from: root.read(root.fd, ".screenpunk-snapshot.json", maxBytes: 8 * 1024 * 1024))
        guard record.sourceHashVersion == 1, record.sourceVersion == requestedVersion,
              record.projectId == project.projectId,
              record.dashboardId == project.dashboardId,
              (1...2_000).contains(record.files.count) else { throw WorkspaceError.invalidSchema }
        let captured = try capture(path: path, project: project)
        guard captured.2 == requestedVersion, captured.1.count == record.files.count else {
            throw WorkspaceError.conflict
        }
        var seen = WorkspacePathCollisionDetector()
        for file in record.files {
            try seen.insert(file.path)
            guard let bytes = captured.1[file.path], bytes.count == file.bytes,
                  WorkbenchTransactionDigest.hex(bytes) == file.sha256 else {
                throw WorkspaceError.conflict
            }
        }
        try root.verifyRoot()
        return captured
    }

    private func topLevelNames(_ directory: Int32) throws -> Set<String> {
        let copy = dup(directory)
        guard copy >= 0, let stream = fdopendir(copy) else {
            if copy >= 0 { close(copy) }; throw WorkspaceError.unavailable
        }
        defer { closedir(stream) }
        var names = Set<String>()
        while true {
            errno = 0
            guard let entry = readdir(stream) else {
                guard errno == 0 else { throw WorkspaceError.unavailable }
                break
            }
            let name = withUnsafePointer(to: &entry.pointee.d_name) { pointer in
                pointer.withMemoryRebound(to: CChar.self,
                    capacity: MemoryLayout.size(ofValue: entry.pointee.d_name)) {
                    String(validatingUTF8: $0)
                }
            }
            guard let name else { throw WorkspaceError.unsafeFile }
            if name != "." && name != ".." { names.insert(name) }
            guard names.count <= 2 else { throw WorkspaceError.invalidSchema }
        }
        return names
    }

    private func removeOwnedStage(parent: WorkspaceFiles, name: String,
                                  stage: WorkspaceFiles) throws {
        let opened = try parent.directory([name]); defer { close(opened) }
        var info = stat()
        guard fstat(opened, &info) == 0, WorkspaceNodeID(info) == stage.identity else {
            throw WorkspaceError.conflict
        }
        try removeChildren(opened, depth: 0)
        guard unlinkat(parent.fd, name, AT_REMOVEDIR) == 0 else { throw WorkspaceError.unavailable }
    }
    private func removeChildren(_ directory: Int32, depth: Int) throws {
        guard depth <= 32 else { throw WorkspaceError.limitExceeded }
        let copy = dup(directory)
        guard copy >= 0, let stream = fdopendir(copy) else {
            if copy >= 0 { close(copy) }; throw WorkspaceError.unavailable
        }
        defer { closedir(stream) }
        var names: [String] = []
        while true {
            errno = 0
            guard let entry = readdir(stream) else {
                guard errno == 0 else { throw WorkspaceError.unavailable }
                break
            }
            let name = withUnsafePointer(to: &entry.pointee.d_name) { pointer in
                pointer.withMemoryRebound(to: CChar.self,
                    capacity: MemoryLayout.size(ofValue: entry.pointee.d_name)) {
                    String(validatingUTF8: $0)
                }
            }
            guard let name else { throw WorkspaceError.unsafeFile }
            if name != "." && name != ".." { names.append(name) }
        }
        guard names.count <= 2_000 else { throw WorkspaceError.limitExceeded }
        for name in names {
            guard WorkspaceValidation.member(name), !name.contains("/") else {
                throw WorkspaceError.invalidPath
            }
            var info = stat()
            guard fstatat(directory, name, &info, AT_SYMLINK_NOFOLLOW) == 0,
                  info.st_uid == geteuid() else { throw WorkspaceError.unsafeFile }
            if info.st_mode & mode_t(S_IFMT) == mode_t(S_IFDIR) {
                let child = openat(directory, name, O_RDONLY | O_DIRECTORY | O_NOFOLLOW | O_CLOEXEC)
                guard child >= 0 else { throw WorkspaceError.unsafeFile }
                defer { close(child) }
                try removeChildren(child, depth: depth + 1)
                guard unlinkat(directory, name, AT_REMOVEDIR) == 0 else { throw WorkspaceError.unavailable }
            } else if info.st_mode & mode_t(S_IFMT) == mode_t(S_IFREG), info.st_nlink == 1 {
                guard unlinkat(directory, name, 0) == 0 else { throw WorkspaceError.unavailable }
            } else { throw WorkspaceError.unsafeFile }
        }
    }
}
#endif
