import Foundation

/// Full-screen preview presets, not an Android runtime or device-support list.
/// Apple sizes use CoreSimulator's logical canvas. Android sizes preserve the
/// manufacturer's panel proportions at a common logical width. See docs/device-preview-catalog.md.
public struct ScreenPreviewProfile: Identifiable, Hashable, Sendable {
    public let name: String
    public let brand: String
    public let kind: String
    public let width: Int
    public let height: Int
    public var id: String { brand + ":" + name }
    public var dimensions: String { "\(width) × \(height)" }
    public var symbol: String { kind == "Phone" ? "iphone.gen3" : "ipad" }
    public static var defaultProfile: Self { all.first { $0.name == "iPhone 13" }! }
    private static func normalized(_ value: String) -> String {
        value.folding(options: [.caseInsensitive, .diacriticInsensitive, .widthInsensitive], locale: Locale(identifier: "en_US_POSIX"))
            .replacingOccurrences(of: "-", with: " ")
    }
    public static func matching(_ query: String) -> [Self] {
        let terms = normalized(query).split(whereSeparator: { $0.isWhitespace })
        return all.filter { profile in
            let text = normalized(profile.brand + " " + profile.name + " " + profile.kind)
            return terms.allSatisfy { text.contains($0) }
        }
    }
    public static let all: [Self] = [
        .init(name: "iPad (10th generation)", brand: "Apple", kind: "Tablet", width: 820, height: 1180),
        .init(name: "iPad (6th generation)", brand: "Apple", kind: "Tablet", width: 768, height: 1024),
        .init(name: "iPad (7th generation)", brand: "Apple", kind: "Tablet", width: 810, height: 1080),
        .init(name: "iPad (8th generation)", brand: "Apple", kind: "Tablet", width: 810, height: 1080),
        .init(name: "iPad (9th generation)", brand: "Apple", kind: "Tablet", width: 810, height: 1080),
        .init(name: "iPad (A16)", brand: "Apple", kind: "Tablet", width: 820, height: 1180),
        .init(name: "iPad Air (3rd generation)", brand: "Apple", kind: "Tablet", width: 834, height: 1112),
        .init(name: "iPad Air (4th generation)", brand: "Apple", kind: "Tablet", width: 820, height: 1180),
        .init(name: "iPad Air (5th generation)", brand: "Apple", kind: "Tablet", width: 820, height: 1180),
        .init(name: "iPad Air 11-inch (M2)", brand: "Apple", kind: "Tablet", width: 820, height: 1180),
        .init(name: "iPad Air 11-inch (M3)", brand: "Apple", kind: "Tablet", width: 820, height: 1180),
        .init(name: "iPad Air 11-inch (M4)", brand: "Apple", kind: "Tablet", width: 820, height: 1180),
        .init(name: "iPad Air 13-inch (M2)", brand: "Apple", kind: "Tablet", width: 1024, height: 1366),
        .init(name: "iPad Air 13-inch (M3)", brand: "Apple", kind: "Tablet", width: 1024, height: 1366),
        .init(name: "iPad Air 13-inch (M4)", brand: "Apple", kind: "Tablet", width: 1024, height: 1366),
        .init(name: "iPad Pro (11-inch) (1st generation)", brand: "Apple", kind: "Tablet", width: 834, height: 1194),
        .init(name: "iPad Pro (11-inch) (2nd generation)", brand: "Apple", kind: "Tablet", width: 834, height: 1194),
        .init(name: "iPad Pro (11-inch) (3rd generation)", brand: "Apple", kind: "Tablet", width: 834, height: 1194),
        .init(name: "iPad Pro (11-inch) (4th generation)", brand: "Apple", kind: "Tablet", width: 834, height: 1194),
        .init(name: "iPad Pro (12.9-inch) (3rd generation)", brand: "Apple", kind: "Tablet", width: 1024, height: 1366),
        .init(name: "iPad Pro (12.9-inch) (4th generation)", brand: "Apple", kind: "Tablet", width: 1024, height: 1366),
        .init(name: "iPad Pro (12.9-inch) (5th generation)", brand: "Apple", kind: "Tablet", width: 1024, height: 1366),
        .init(name: "iPad Pro (12.9-inch) (6th generation)", brand: "Apple", kind: "Tablet", width: 1024, height: 1366),
        .init(name: "iPad Pro 11-inch (M4)", brand: "Apple", kind: "Tablet", width: 834, height: 1210),
        .init(name: "iPad Pro 11-inch (M5)", brand: "Apple", kind: "Tablet", width: 834, height: 1210),
        .init(name: "iPad Pro 13-inch (M4)", brand: "Apple", kind: "Tablet", width: 1032, height: 1376),
        .init(name: "iPad Pro 13-inch (M5)", brand: "Apple", kind: "Tablet", width: 1032, height: 1376),
        .init(name: "iPad mini (5th generation)", brand: "Apple", kind: "Tablet", width: 768, height: 1024),
        .init(name: "iPad mini (6th generation)", brand: "Apple", kind: "Tablet", width: 744, height: 1133),
        .init(name: "iPad mini (A17 Pro)", brand: "Apple", kind: "Tablet", width: 744, height: 1133),
        .init(name: "iPhone 11 Pro Max", brand: "Apple", kind: "Phone", width: 414, height: 896),
        .init(name: "iPhone 11 Pro", brand: "Apple", kind: "Phone", width: 375, height: 812),
        .init(name: "iPhone 11", brand: "Apple", kind: "Phone", width: 414, height: 896),
        .init(name: "iPhone 12 Pro Max", brand: "Apple", kind: "Phone", width: 428, height: 926),
        .init(name: "iPhone 12 Pro", brand: "Apple", kind: "Phone", width: 390, height: 844),
        .init(name: "iPhone 12 mini", brand: "Apple", kind: "Phone", width: 375, height: 812),
        .init(name: "iPhone 12", brand: "Apple", kind: "Phone", width: 390, height: 844),
        .init(name: "iPhone 13 Pro Max", brand: "Apple", kind: "Phone", width: 428, height: 926),
        .init(name: "iPhone 13 Pro", brand: "Apple", kind: "Phone", width: 390, height: 844),
        .init(name: "iPhone 13 mini", brand: "Apple", kind: "Phone", width: 375, height: 812),
        .init(name: "iPhone 13", brand: "Apple", kind: "Phone", width: 390, height: 844),
        .init(name: "iPhone 14 Plus", brand: "Apple", kind: "Phone", width: 428, height: 926),
        .init(name: "iPhone 14 Pro Max", brand: "Apple", kind: "Phone", width: 430, height: 932),
        .init(name: "iPhone 14 Pro", brand: "Apple", kind: "Phone", width: 393, height: 852),
        .init(name: "iPhone 14", brand: "Apple", kind: "Phone", width: 390, height: 844),
        .init(name: "iPhone 15 Plus", brand: "Apple", kind: "Phone", width: 430, height: 932),
        .init(name: "iPhone 15 Pro Max", brand: "Apple", kind: "Phone", width: 430, height: 932),
        .init(name: "iPhone 15 Pro", brand: "Apple", kind: "Phone", width: 393, height: 852),
        .init(name: "iPhone 15", brand: "Apple", kind: "Phone", width: 393, height: 852),
        .init(name: "iPhone 16 Plus", brand: "Apple", kind: "Phone", width: 430, height: 932),
        .init(name: "iPhone 16 Pro Max", brand: "Apple", kind: "Phone", width: 440, height: 956),
        .init(name: "iPhone 16 Pro", brand: "Apple", kind: "Phone", width: 402, height: 874),
        .init(name: "iPhone 16", brand: "Apple", kind: "Phone", width: 393, height: 852),
        .init(name: "iPhone 16e", brand: "Apple", kind: "Phone", width: 390, height: 844),
        .init(name: "iPhone 17 Pro Max", brand: "Apple", kind: "Phone", width: 440, height: 956),
        .init(name: "iPhone 17 Pro", brand: "Apple", kind: "Phone", width: 402, height: 874),
        .init(name: "iPhone 17", brand: "Apple", kind: "Phone", width: 402, height: 874),
        .init(name: "iPhone 17e", brand: "Apple", kind: "Phone", width: 390, height: 844),
        .init(name: "iPhone Air", brand: "Apple", kind: "Phone", width: 420, height: 912),
        .init(name: "iPhone SE (2nd generation)", brand: "Apple", kind: "Phone", width: 375, height: 667),
        .init(name: "iPhone SE (3rd generation)", brand: "Apple", kind: "Phone", width: 375, height: 667),
        .init(name: "iPhone XS Max", brand: "Apple", kind: "Phone", width: 414, height: 896),
        .init(name: "iPhone XS", brand: "Apple", kind: "Phone", width: 375, height: 812),
        .init(name: "iPhone XR", brand: "Apple", kind: "Phone", width: 414, height: 896),
        .init(name: "Galaxy S26 FE", brand: "Samsung", kind: "Phone", width: 412, height: 893),
        .init(name: "Galaxy S26 Ultra", brand: "Samsung", kind: "Phone", width: 412, height: 893),
        .init(name: "Galaxy S26+", brand: "Samsung", kind: "Phone", width: 412, height: 893),
        .init(name: "Galaxy S26", brand: "Samsung", kind: "Phone", width: 412, height: 893),
        .init(name: "Galaxy S25 FE", brand: "Samsung", kind: "Phone", width: 412, height: 893),
        .init(name: "Galaxy S25 Edge", brand: "Samsung", kind: "Phone", width: 412, height: 893),
        .init(name: "Galaxy S25 Ultra", brand: "Samsung", kind: "Phone", width: 412, height: 893),
        .init(name: "Galaxy S25+", brand: "Samsung", kind: "Phone", width: 412, height: 893),
        .init(name: "Galaxy S25", brand: "Samsung", kind: "Phone", width: 412, height: 893),
        .init(name: "Galaxy S24 FE", brand: "Samsung", kind: "Phone", width: 412, height: 893),
        .init(name: "Galaxy S24 Ultra", brand: "Samsung", kind: "Phone", width: 412, height: 893),
        .init(name: "Galaxy S24+", brand: "Samsung", kind: "Phone", width: 412, height: 893),
        .init(name: "Galaxy S24", brand: "Samsung", kind: "Phone", width: 412, height: 893),
        .init(name: "Galaxy S23 FE", brand: "Samsung", kind: "Phone", width: 412, height: 893),
        .init(name: "Galaxy S23 Ultra", brand: "Samsung", kind: "Phone", width: 412, height: 884),
        .init(name: "Galaxy S23+", brand: "Samsung", kind: "Phone", width: 412, height: 893),
        .init(name: "Galaxy S23", brand: "Samsung", kind: "Phone", width: 412, height: 893),
        .init(name: "Galaxy S22 Ultra", brand: "Samsung", kind: "Phone", width: 412, height: 884),
        .init(name: "Galaxy S22+", brand: "Samsung", kind: "Phone", width: 412, height: 893),
        .init(name: "Galaxy S22", brand: "Samsung", kind: "Phone", width: 412, height: 893),
        .init(name: "Galaxy S21 FE", brand: "Samsung", kind: "Phone", width: 412, height: 916),
        .init(name: "Galaxy S21 Ultra", brand: "Samsung", kind: "Phone", width: 412, height: 916),
        .init(name: "Galaxy S21+", brand: "Samsung", kind: "Phone", width: 412, height: 916),
        .init(name: "Galaxy S21", brand: "Samsung", kind: "Phone", width: 412, height: 916),
        .init(name: "Galaxy S20 FE", brand: "Samsung", kind: "Phone", width: 412, height: 916),
        .init(name: "Galaxy S20 Ultra", brand: "Samsung", kind: "Phone", width: 412, height: 916),
        .init(name: "Galaxy S20+", brand: "Samsung", kind: "Phone", width: 412, height: 916),
        .init(name: "Galaxy S20", brand: "Samsung", kind: "Phone", width: 412, height: 916),
        .init(name: "Galaxy S10+", brand: "Samsung", kind: "Phone", width: 412, height: 870),
        .init(name: "Galaxy S10", brand: "Samsung", kind: "Phone", width: 412, height: 870),
        .init(name: "Galaxy S10e", brand: "Samsung", kind: "Phone", width: 412, height: 870),
        .init(name: "Galaxy S10 Lite", brand: "Samsung", kind: "Phone", width: 412, height: 916),
        .init(name: "Galaxy S9+", brand: "Samsung", kind: "Phone", width: 412, height: 847),
        .init(name: "Galaxy S9", brand: "Samsung", kind: "Phone", width: 412, height: 847),
        .init(name: "Galaxy A27 5G", brand: "Samsung", kind: "Phone", width: 412, height: 893),
        .init(name: "Galaxy A57 5G", brand: "Samsung", kind: "Phone", width: 412, height: 893),
        .init(name: "Galaxy A37 5G", brand: "Samsung", kind: "Phone", width: 412, height: 893),
        .init(name: "Galaxy A07", brand: "Samsung", kind: "Phone", width: 412, height: 916),
        .init(name: "Galaxy A17 5G", brand: "Samsung", kind: "Phone", width: 412, height: 893),
        .init(name: "Galaxy A26 5G", brand: "Samsung", kind: "Phone", width: 412, height: 893),
        .init(name: "Galaxy A56 5G", brand: "Samsung", kind: "Phone", width: 412, height: 893),
        .init(name: "Galaxy A36 5G", brand: "Samsung", kind: "Phone", width: 412, height: 893),
        .init(name: "Galaxy A16 5G", brand: "Samsung", kind: "Phone", width: 412, height: 893),
        .init(name: "Galaxy A06", brand: "Samsung", kind: "Phone", width: 412, height: 916),
        .init(name: "Galaxy A55 5G", brand: "Samsung", kind: "Phone", width: 412, height: 893),
        .init(name: "Galaxy A35 5G", brand: "Samsung", kind: "Phone", width: 412, height: 893),
        .init(name: "Galaxy A25 5G", brand: "Samsung", kind: "Phone", width: 412, height: 893),
        .init(name: "Galaxy A15 5G", brand: "Samsung", kind: "Phone", width: 412, height: 893),
        .init(name: "Galaxy A05", brand: "Samsung", kind: "Phone", width: 412, height: 916),
        .init(name: "Galaxy A05s", brand: "Samsung", kind: "Phone", width: 412, height: 916),
        .init(name: "Galaxy A24", brand: "Samsung", kind: "Phone", width: 412, height: 893),
        .init(name: "Galaxy A23 5G", brand: "Samsung", kind: "Phone", width: 412, height: 919),
        .init(name: "Galaxy A14 5G", brand: "Samsung", kind: "Phone", width: 412, height: 919),
        .init(name: "Galaxy A04", brand: "Samsung", kind: "Phone", width: 412, height: 916),
        .init(name: "Galaxy A54 5G", brand: "Samsung", kind: "Phone", width: 412, height: 893),
        .init(name: "Galaxy A34 5G", brand: "Samsung", kind: "Phone", width: 412, height: 893),
        .init(name: "Galaxy A73 5G", brand: "Samsung", kind: "Phone", width: 412, height: 916),
        .init(name: "Galaxy A53 5G", brand: "Samsung", kind: "Phone", width: 412, height: 916),
        .init(name: "Galaxy A33 5G", brand: "Samsung", kind: "Phone", width: 412, height: 916),
        .init(name: "Galaxy A13 5G", brand: "Samsung", kind: "Phone", width: 412, height: 916),
        .init(name: "Galaxy A03s", brand: "Samsung", kind: "Phone", width: 412, height: 916),
        .init(name: "Galaxy A12", brand: "Samsung", kind: "Phone", width: 412, height: 916),
        .init(name: "Galaxy A11", brand: "Samsung", kind: "Phone", width: 412, height: 893),
        .init(name: "Galaxy A01 Core", brand: "Samsung", kind: "Phone", width: 412, height: 847),
        .init(name: "Galaxy A42 5G", brand: "Samsung", kind: "Phone", width: 412, height: 916),
        .init(name: "Galaxy A22 5G", brand: "Samsung", kind: "Phone", width: 412, height: 916),
        .init(name: "Galaxy A22", brand: "Samsung", kind: "Phone", width: 412, height: 916),
        .init(name: "Galaxy A32 5G", brand: "Samsung", kind: "Phone", width: 412, height: 916),
        .init(name: "Galaxy A32", brand: "Samsung", kind: "Phone", width: 412, height: 916),
        .init(name: "Galaxy A02s", brand: "Samsung", kind: "Phone", width: 412, height: 916),
        .init(name: "Galaxy A72", brand: "Samsung", kind: "Phone", width: 412, height: 916),
        .init(name: "Galaxy A52", brand: "Samsung", kind: "Phone", width: 412, height: 916),
        .init(name: "Galaxy A71", brand: "Samsung", kind: "Phone", width: 412, height: 916),
        .init(name: "Galaxy A31", brand: "Samsung", kind: "Phone", width: 412, height: 916),
        .init(name: "Galaxy A21s", brand: "Samsung", kind: "Phone", width: 412, height: 916),
        .init(name: "Galaxy A51", brand: "Samsung", kind: "Phone", width: 412, height: 916),
        .init(name: "Galaxy Tab A11+", brand: "Samsung", kind: "Tablet", width: 800, height: 1280),
        .init(name: "Galaxy Tab A11", brand: "Samsung", kind: "Tablet", width: 800, height: 1340),
        .init(name: "Galaxy Tab S11 Ultra", brand: "Samsung", kind: "Tablet", width: 800, height: 1281),
        .init(name: "Galaxy Tab S11", brand: "Samsung", kind: "Tablet", width: 800, height: 1280),
        .init(name: "Galaxy Tab S10 FE+", brand: "Samsung", kind: "Tablet", width: 800, height: 1280),
        .init(name: "Galaxy Tab S10 FE", brand: "Samsung", kind: "Tablet", width: 800, height: 1280),
        .init(name: "Galaxy Tab S10 Ultra", brand: "Samsung", kind: "Tablet", width: 800, height: 1281),
        .init(name: "Galaxy Tab S10+", brand: "Samsung", kind: "Tablet", width: 800, height: 1279),
        .init(name: "Galaxy Tab A9+", brand: "Samsung", kind: "Tablet", width: 800, height: 1280),
        .init(name: "Galaxy Tab A9", brand: "Samsung", kind: "Tablet", width: 800, height: 1340),
        .init(name: "Galaxy Tab S9 FE+", brand: "Samsung", kind: "Tablet", width: 800, height: 1280),
        .init(name: "Galaxy Tab S9 FE", brand: "Samsung", kind: "Tablet", width: 800, height: 1280),
        .init(name: "Galaxy Tab S9 Ultra", brand: "Samsung", kind: "Tablet", width: 800, height: 1281),
        .init(name: "Galaxy Tab S9+", brand: "Samsung", kind: "Tablet", width: 800, height: 1279),
        .init(name: "Galaxy Tab S9", brand: "Samsung", kind: "Tablet", width: 800, height: 1280),
        .init(name: "Galaxy Tab A8 10.5 (2021)", brand: "Samsung", kind: "Tablet", width: 800, height: 1280),
        .init(name: "Galaxy Tab A7 10.4 (2022)", brand: "Samsung", kind: "Tablet", width: 800, height: 1333),
        .init(name: "Galaxy Tab S8 Ultra", brand: "Samsung", kind: "Tablet", width: 800, height: 1281),
        .init(name: "Galaxy Tab S8+", brand: "Samsung", kind: "Tablet", width: 800, height: 1279),
        .init(name: "Galaxy Tab S8", brand: "Samsung", kind: "Tablet", width: 800, height: 1280),
        .init(name: "Galaxy Tab S7+", brand: "Samsung", kind: "Tablet", width: 800, height: 1279),
        .init(name: "Galaxy Tab S7", brand: "Samsung", kind: "Tablet", width: 800, height: 1280),
        .init(name: "Galaxy Tab A7 Lite", brand: "Samsung", kind: "Tablet", width: 800, height: 1340),
        .init(name: "Galaxy Tab S7 FE", brand: "Samsung", kind: "Tablet", width: 800, height: 1280),
        .init(name: "Galaxy Tab A 10.5", brand: "Samsung", kind: "Tablet", width: 800, height: 1280),
        .init(name: "Galaxy Tab S4 10.5", brand: "Samsung", kind: "Tablet", width: 800, height: 1280),
        .init(name: "Galaxy Tab S6 Lite", brand: "Samsung", kind: "Tablet", width: 800, height: 1333),
        .init(name: "Galaxy Tab S6", brand: "Samsung", kind: "Tablet", width: 800, height: 1280),
        .init(name: "Galaxy Tab S5e", brand: "Samsung", kind: "Tablet", width: 800, height: 1280),
        .init(name: "Galaxy Tab A 10.1 (2019)", brand: "Samsung", kind: "Tablet", width: 800, height: 1280),
        .init(name: "Galaxy Tab A 8.0 (2019)", brand: "Samsung", kind: "Tablet", width: 800, height: 1280),
        .init(name: "Galaxy Z Fold8 Ultra — Inner", brand: "Samsung", kind: "Foldable", width: 800, height: 888),
        .init(name: "Galaxy Z Fold8 — Inner", brand: "Samsung", kind: "Foldable", width: 800, height: 1071),
        .init(name: "Galaxy Z Flip8 — Main", brand: "Samsung", kind: "Phone", width: 412, height: 961),
        .init(name: "Galaxy Z TriFold — Inner", brand: "Samsung", kind: "Foldable", width: 800, height: 1091),
        .init(name: "Galaxy Z Fold7 — Inner", brand: "Samsung", kind: "Foldable", width: 800, height: 888),
        .init(name: "Galaxy Z Flip7 — Main", brand: "Samsung", kind: "Phone", width: 412, height: 961),
        .init(name: "Galaxy Z Flip7 FE — Main", brand: "Samsung", kind: "Phone", width: 412, height: 1007),
        .init(name: "Galaxy Z Fold6 — Inner", brand: "Samsung", kind: "Foldable", width: 800, height: 931),
        .init(name: "Galaxy Z Flip6 — Main", brand: "Samsung", kind: "Phone", width: 412, height: 1007),
        .init(name: "Galaxy Z Fold5 — Inner", brand: "Samsung", kind: "Foldable", width: 800, height: 961),
        .init(name: "Galaxy Z Flip5 — Main", brand: "Samsung", kind: "Phone", width: 412, height: 1007),
        .init(name: "Galaxy Z Fold4 — Inner", brand: "Samsung", kind: "Foldable", width: 800, height: 961),
        .init(name: "Galaxy Z Flip4 — Main", brand: "Samsung", kind: "Phone", width: 412, height: 1007),
        .init(name: "Galaxy Z Fold3 — Inner", brand: "Samsung", kind: "Foldable", width: 800, height: 999),
        .init(name: "Galaxy Z Flip3 — Main", brand: "Samsung", kind: "Phone", width: 412, height: 1007),
        .init(name: "Galaxy Z Fold2 — Inner", brand: "Samsung", kind: "Foldable", width: 800, height: 999),
        .init(name: "Galaxy Z Flip — Main", brand: "Samsung", kind: "Phone", width: 412, height: 1006),
        .init(name: "Galaxy Fold — Inner", brand: "Samsung", kind: "Foldable", width: 800, height: 1121),
        .init(name: "Galaxy Note20 Ultra", brand: "Samsung", kind: "Phone", width: 412, height: 884),
        .init(name: "Galaxy Note20", brand: "Samsung", kind: "Phone", width: 412, height: 916),
        .init(name: "Galaxy Note10+", brand: "Samsung", kind: "Phone", width: 412, height: 870),
        .init(name: "Galaxy Note10", brand: "Samsung", kind: "Phone", width: 412, height: 870),
        .init(name: "Galaxy Note10 Lite", brand: "Samsung", kind: "Phone", width: 412, height: 916),
        .init(name: "Galaxy Note9", brand: "Samsung", kind: "Phone", width: 412, height: 847),
        .init(name: "Pixel 11 Pro Fold — Outer", brand: "Google", kind: "Phone", width: 412, height: 893),
        .init(name: "Pixel 11 Pro Fold — Inner", brand: "Google", kind: "Foldable", width: 800, height: 829),
        .init(name: "Pixel 11 Pro XL", brand: "Google", kind: "Phone", width: 412, height: 917),
        .init(name: "Pixel 11 Pro", brand: "Google", kind: "Phone", width: 412, height: 919),
        .init(name: "Pixel 11", brand: "Google", kind: "Phone", width: 412, height: 925),
        .init(name: "Pixel 10a", brand: "Google", kind: "Phone", width: 412, height: 925),
        .init(name: "Pixel 10 Pro Fold — Outer", brand: "Google", kind: "Phone", width: 412, height: 902),
        .init(name: "Pixel 10 Pro Fold — Inner", brand: "Google", kind: "Foldable", width: 800, height: 829),
        .init(name: "Pixel 10 Pro XL", brand: "Google", kind: "Phone", width: 412, height: 917),
        .init(name: "Pixel 10 Pro", brand: "Google", kind: "Phone", width: 412, height: 919),
        .init(name: "Pixel 10", brand: "Google", kind: "Phone", width: 412, height: 925),
        .init(name: "Pixel 9a", brand: "Google", kind: "Phone", width: 412, height: 925),
        .init(name: "Pixel 9 Pro Fold — Outer", brand: "Google", kind: "Phone", width: 412, height: 925),
        .init(name: "Pixel 9 Pro Fold — Inner", brand: "Google", kind: "Foldable", width: 800, height: 829),
        .init(name: "Pixel 9 Pro XL", brand: "Google", kind: "Phone", width: 412, height: 917),
        .init(name: "Pixel 9 Pro", brand: "Google", kind: "Phone", width: 412, height: 919),
        .init(name: "Pixel 9", brand: "Google", kind: "Phone", width: 412, height: 925),
        .init(name: "Pixel 8a", brand: "Google", kind: "Phone", width: 412, height: 916),
        .init(name: "Pixel 8 Pro", brand: "Google", kind: "Phone", width: 412, height: 917),
        .init(name: "Pixel 8", brand: "Google", kind: "Phone", width: 412, height: 916),
        .init(name: "Pixel Fold — Outer", brand: "Google", kind: "Phone", width: 412, height: 798),
        .init(name: "Pixel Fold — Inner", brand: "Google", kind: "Foldable", width: 800, height: 960),
        .init(name: "Pixel 7a", brand: "Google", kind: "Phone", width: 412, height: 916),
        .init(name: "Pixel 7 Pro", brand: "Google", kind: "Phone", width: 412, height: 893),
        .init(name: "Pixel 7", brand: "Google", kind: "Phone", width: 412, height: 916),
        .init(name: "Pixel 6a", brand: "Google", kind: "Phone", width: 412, height: 916),
        .init(name: "Pixel 6 Pro", brand: "Google", kind: "Phone", width: 412, height: 893),
        .init(name: "Pixel 6", brand: "Google", kind: "Phone", width: 412, height: 916),
        .init(name: "Pixel 3", brand: "Google", kind: "Phone", width: 412, height: 824),
        .init(name: "Pixel 3 XL", brand: "Google", kind: "Phone", width: 412, height: 847),
        .init(name: "Pixel 3a", brand: "Google", kind: "Phone", width: 412, height: 847),
        .init(name: "Pixel 3a XL", brand: "Google", kind: "Phone", width: 412, height: 824),
        .init(name: "Pixel 4", brand: "Google", kind: "Phone", width: 412, height: 870),
        .init(name: "Pixel 4 XL", brand: "Google", kind: "Phone", width: 412, height: 870),
        .init(name: "Pixel 4a", brand: "Google", kind: "Phone", width: 412, height: 893),
        .init(name: "Pixel 4a 5G", brand: "Google", kind: "Phone", width: 412, height: 893),
        .init(name: "Pixel 5", brand: "Google", kind: "Phone", width: 412, height: 893),
        .init(name: "Pixel 5a 5G", brand: "Google", kind: "Phone", width: 412, height: 916),
        .init(name: "OnePlus 13", brand: "OnePlus", kind: "Phone", width: 412, height: 906),
        .init(name: "Redmi Note 13", brand: "Xiaomi", kind: "Phone", width: 412, height: 916),
        .init(name: "Redmi Note 12", brand: "Xiaomi", kind: "Phone", width: 412, height: 916),
        .init(name: "moto g power 5G (2023)", brand: "Motorola", kind: "Phone", width: 412, height: 916),
    ].sorted {
        if $0.brand != $1.brand { return $0.brand < $1.brand }
        return $0.name.localizedStandardCompare($1.name) == .orderedAscending
    }
}
